"""
report_builder.py
────────────────────────────────────────────────────────
Builds a formatted Excel summary report from sales_data.csv.
Called by the email bot before sending.
────────────────────────────────────────────────────────
"""

import pandas as pd
import numpy as np
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, Reference
from datetime import datetime, timedelta
import os

# ── Palette ────────────────────────────────────────────────────
DARK_GREEN  = "145A32"
MID_GREEN   = "1E8449"
LIGHT_GREEN = "D5F5E3"
ACCENT      = "F39C12"
WHITE       = "FFFFFF"
LIGHT_GRAY  = "F4F6F7"
DARK_GRAY   = "2C3E50"

def _border():
    s = Side(style="thin", color="CCCCCC")
    return Border(left=s, right=s, top=s, bottom=s)

def _fill(hex_color):
    return PatternFill("solid", fgColor=hex_color)

def _font(size=10, bold=False, color=DARK_GRAY):
    return Font(name="Calibri", size=size, bold=bold, color=color)

def _center():
    return Alignment(horizontal="center", vertical="center", wrap_text=True)

def autofit(ws, min_w=12, max_w=40):
    for col in ws.columns:
        max_len = max((len(str(c.value)) for c in col if c.value), default=8)
        ws.column_dimensions[get_column_letter(col[0].column)].width = min(max(max_len + 2, min_w), max_w)

def write_header_row(ws, row, cols):
    for ci, col in enumerate(cols, 1):
        c = ws.cell(row=row, column=ci, value=col)
        c.font      = _font(bold=True, color=WHITE)
        c.fill      = _fill(MID_GREEN)
        c.alignment = _center()
        c.border    = _border()

def write_data_row(ws, row, values, shade=False):
    bg = LIGHT_GREEN if shade else WHITE
    for ci, val in enumerate(values, 1):
        c = ws.cell(row=row, column=ci, value=val)
        c.font      = _font()
        c.fill      = _fill(bg)
        c.alignment = _center()
        c.border    = _border()

def build_report(csv_path="sales_data.csv"):
    df = pd.read_csv(csv_path)
    df["Date"]    = pd.to_datetime(df["Date"])
    df["Revenue"] = pd.to_numeric(df["Revenue"], errors="coerce")
    completed     = df[df["Status"] == "Completed"]

    today     = datetime.today().date()
    yesterday = today - timedelta(days=1)
    last_7    = today - timedelta(days=7)

    # ── KPIs ────────────────────────────────────────────────────
    kpis = {
        "Report Date":           str(today),
        "Total Orders (30d)":    len(df),
        "Completed Orders":      len(completed),
        "Total Revenue (30d)":   f"${completed['Revenue'].sum():,.2f}",
        "Yesterday Revenue":     f"${completed[completed['Date'].dt.date == yesterday]['Revenue'].sum():,.2f}",
        "Last 7 Days Revenue":   f"${completed[completed['Date'].dt.date >= last_7]['Revenue'].sum():,.2f}",
        "Top Product":           completed.groupby("Product")["Revenue"].sum().idxmax(),
        "Top Sales Rep":         completed.groupby("Sales_Rep")["Revenue"].sum().idxmax(),
        "Return Rate":           f"{len(df[df['Status']=='Returned'])/len(df)*100:.1f}%",
    }

    # ── Aggregations ────────────────────────────────────────────
    daily = (completed.groupby(completed["Date"].dt.strftime("%Y-%m-%d"))
                       .agg(Orders=("Order_ID","count"), Revenue=("Revenue","sum"))
                       .reset_index().rename(columns={"Date":"Day"}))
    daily["Revenue"] = daily["Revenue"].round(2)

    by_product = (completed.groupby("Product")
                            .agg(Revenue=("Revenue","sum"), Units=("Quantity","sum"))
                            .reset_index().sort_values("Revenue", ascending=False))
    by_product["Revenue"] = by_product["Revenue"].round(2)

    by_rep = (completed.groupby("Sales_Rep")
                        .agg(Revenue=("Revenue","sum"), Orders=("Order_ID","count"))
                        .reset_index().sort_values("Revenue", ascending=False))
    by_rep["Revenue"] = by_rep["Revenue"].round(2)
    by_rep.insert(0, "Rank", range(1, len(by_rep)+1))

    # ── Build Workbook ───────────────────────────────────────────
    wb = Workbook()

    # Sheet 1: Summary
    ws1 = wb.active
    ws1.title = "Summary"
    ws1.sheet_view.showGridLines = False

    ws1.merge_cells("A1:D1")
    c = ws1["A1"]
    c.value     = f"📊  DAILY SALES REPORT  —  {today.strftime('%B %d, %Y')}"
    c.font      = Font(name="Calibri", size=14, bold=True, color=WHITE)
    c.fill      = _fill(DARK_GREEN)
    c.alignment = _center()
    ws1.row_dimensions[1].height = 35

    ws1.merge_cells("A2:D2")
    s = ws1["A2"]
    s.value     = "Auto-generated by Scheduled Email Report Bot"
    s.font      = Font(name="Calibri", size=9, italic=True, color="888888")
    s.alignment = _center()

    # KPI table
    ws1.cell(row=4, column=1, value="KPI").font  = _font(bold=True, color=WHITE)
    ws1.cell(row=4, column=1).fill               = _fill(MID_GREEN)
    ws1.cell(row=4, column=1).alignment          = _center()
    ws1.cell(row=4, column=1).border             = _border()
    ws1.cell(row=4, column=2, value="Value").font = _font(bold=True, color=WHITE)
    ws1.cell(row=4, column=2).fill               = _fill(MID_GREEN)
    ws1.cell(row=4, column=2).alignment          = _center()
    ws1.cell(row=4, column=2).border             = _border()

    for i, (k, v) in enumerate(kpis.items()):
        bg = LIGHT_GREEN if i % 2 == 0 else WHITE
        ws1.cell(row=5+i, column=1, value=k).fill      = _fill(bg)
        ws1.cell(row=5+i, column=1).font               = _font(bold=True)
        ws1.cell(row=5+i, column=1).border             = _border()
        ws1.cell(row=5+i, column=1).alignment          = _center()
        ws1.cell(row=5+i, column=2, value=str(v)).fill = _fill(bg)
        ws1.cell(row=5+i, column=2).font               = Font(name="Calibri", size=11, bold=True, color=ACCENT)
        ws1.cell(row=5+i, column=2).border             = _border()
        ws1.cell(row=5+i, column=2).alignment          = _center()

    for c, w in [(1, 28), (2, 22), (3, 16), (4, 16)]:
        ws1.column_dimensions[get_column_letter(c)].width = w

    # Sheet 2: Daily Trend
    ws2 = wb.create_sheet("Daily Trend")
    ws2.sheet_view.showGridLines = False
    ws2.merge_cells("A1:C1")
    h = ws2["A1"]
    h.value     = "DAILY REVENUE TREND (LAST 30 DAYS)"
    h.font      = Font(name="Calibri", size=12, bold=True, color=WHITE)
    h.fill      = _fill(DARK_GREEN)
    h.alignment = _center()
    ws2.row_dimensions[1].height = 28

    write_header_row(ws2, 2, ["Date", "Orders", "Revenue ($)"])
    for i, (_, row) in enumerate(daily.iterrows()):
        write_data_row(ws2, 3+i, [row["Day"], row["Orders"], row["Revenue"]], shade=i%2==0)

    chart = BarChart()
    chart.type  = "col"
    chart.title = "Daily Revenue"
    chart.height, chart.width = 12, 22
    chart.style = 10
    data_ref   = Reference(ws2, min_col=3, min_row=2, max_row=2+len(daily))
    labels_ref = Reference(ws2, min_col=1, min_row=3, max_row=2+len(daily))
    chart.add_data(data_ref, titles_from_data=True)
    chart.set_categories(labels_ref)
    ws2.add_chart(chart, "E2")
    autofit(ws2)

    # Sheet 3: By Product
    ws3 = wb.create_sheet("By Product")
    ws3.sheet_view.showGridLines = False
    ws3.merge_cells("A1:C1")
    h = ws3["A1"]
    h.value     = "REVENUE BY PRODUCT"
    h.font      = Font(name="Calibri", size=12, bold=True, color=WHITE)
    h.fill      = _fill(DARK_GREEN)
    h.alignment = _center()
    ws3.row_dimensions[1].height = 28
    write_header_row(ws3, 2, ["Product", "Revenue ($)", "Units Sold"])
    for i, (_, row) in enumerate(by_product.iterrows()):
        write_data_row(ws3, 3+i, [row["Product"], row["Revenue"], row["Units"]], shade=i%2==0)
    autofit(ws3)

    # Sheet 4: Leaderboard
    ws4 = wb.create_sheet("Rep Leaderboard")
    ws4.sheet_view.showGridLines = False
    ws4.merge_cells("A1:D1")
    h = ws4["A1"]
    h.value     = "SALES REP LEADERBOARD"
    h.font      = Font(name="Calibri", size=12, bold=True, color=WHITE)
    h.fill      = _fill(DARK_GREEN)
    h.alignment = _center()
    ws4.row_dimensions[1].height = 28
    medals = {1:"🥇", 2:"🥈", 3:"🥉"}
    write_header_row(ws4, 2, ["Rank", "Sales Rep", "Revenue ($)", "Orders"])
    for i, (_, row) in enumerate(by_rep.iterrows()):
        rank_label = f"{medals.get(int(row['Rank']),'')} #{int(row['Rank'])}"
        write_data_row(ws4, 3+i, [rank_label, row["Sales_Rep"], row["Revenue"], row["Orders"]], shade=i%2==0)
    autofit(ws4)

    # Save
    ts          = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = f"Daily_Sales_Report_{ts}.xlsx"
    wb.save(output_path)
    size_kb = round(os.path.getsize(output_path) / 1024, 1)
    print(f"✅  Report built → {output_path}  ({size_kb} KB)")
    return output_path, kpis
